# Generated by Django 5.0.3 on 2024-09-22 20:03

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0002_user_groups_user_is_active_user_is_staff_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('orgId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=125)),
                ('description', models.TextField()),
                ('organization', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
